spring:
  application:
    name: tosrean
  datasource:
    url: jdbc:postgresql://localhost:5432/words
    username: tosrean
    password: tosrean123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 1GB
  banner:
    location: classpath:banner/banner.txt
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#    url: http://localhost:8080/v3/api-docs
#  swagger-ui:
#      path: /swagger-ui.html

